# Generated by Django 3.2.8 on 2021-10-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notificationadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationadmin',
            old_name='adminupload',
            new_name='adminuploadnotice',
        ),
        migrations.RenameField(
            model_name='notificationadmin',
            old_name='title',
            new_name='noticetitle',
        ),
    ]
