# Generated by Django 3.2.8 on 2021-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_notificationadmin_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('grno', models.CharField(max_length=150)),
                ('mobno', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('classdiv', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
            ],
        ),
    ]
