# Generated by Django 3.2.8 on 2021-10-19 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_testprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('grno', models.CharField(max_length=150)),
                ('mobno', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('classdiv', models.CharField(max_length=150)),
                ('rollno', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
