# Generated by Django 3.2.8 on 2021-10-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_imgprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imgprofile',
        ),
    ]
