# Generated by Django 3.2.8 on 2021-10-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_imgprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='testprofile',
            name='profile_pic',
        ),
    ]
