# Generated by Django 3.2.8 on 2021-10-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211019_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprofile',
            name='grno',
        ),
    ]
