# Generated by Django 3.2.8 on 2021-10-21 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
