# Generated by Django 3.2.8 on 2021-10-21 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211021_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(max_length=150)),
            ],
        ),
    ]
