# Generated by Django 3.2.8 on 2021-10-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_testattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='atten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lecture')),
            ],
        ),
    ]
