# Generated by Django 3.2.8 on 2021-10-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_atten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atten',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.lecture'),
        ),
    ]
