# Generated by Django 3.2.8 on 2021-10-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_atten_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testattendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testattendance',
            name='user',
        ),
        migrations.DeleteModel(
            name='atten',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Testattendance',
        ),
    ]
